import React, { useState, useEffect } from 'react';
import { Copy, Check } from 'lucide-react';
import ScrollReveal from './ScrollReveal';

const SNIPPETS = [
  {
    id: 'terraform',
    label: 'Terraform',
    lang: 'hcl',
    code: `# Generated by InfraSense
resource "aws_instance" "app_server" {
  ami           = "ami-0c55b159cbfafe1f0"
  instance_type = "t3.medium"
  count         = 2

  root_block_device {
    volume_size = 100
    volume_type = "gp3"
    iops        = 3000
  }

  tags = {
    Name = "infrasence-compute-node"
  }
}`,
  },
  {
    id: 'rule',
    label: 'Rule Engine',
    lang: 'javascript',
    code: `// Custom heuristic rule
{
  id: 'high_mem_db_rule',
  name: 'Database Memory Boost',
  condition: (input) => input.workload === 'database',
  applyWeight: (instance) => {
    if (instance.family.startsWith('r')) {
      return 25; // +25 score boost
    }
    return 0;
  }
}`,
  },
  {
    id: 'docker',
    label: 'Docker',
    lang: 'dockerfile',
    code: `# Multi-stage build for cloud deployment
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --production=false
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD ["node", "dist/server.js"]`,
  },
];

function highlightLine(line, lang) {
  if (lang === 'hcl') {
    return line
      .replace(/(#.*)$/g, '<span class="text-slate-500">$1</span>')
      .replace(/"(.*?)"/g, '<span class="text-emerald-300">"$1"</span>')
      .replace(/\b(resource|provider|tags|count)\b/g, '<span class="text-purple-400">$1</span>')
      .replace(/\b(aws_\w+)\b/g, '<span class="text-sky-400">$1</span>');
  }
  if (lang === 'javascript') {
    return line
      .replace(/(\/\/.*)$/g, '<span class="text-slate-500">$1</span>')
      .replace(/"(.*?)"/g, '<span class="text-emerald-300">"$1"</span>')
      .replace(/\b(return|if|const|function)\b/g, '<span class="text-purple-400">$1</span>')
      .replace(/\b(\d+)\b/g, '<span class="text-amber-400">$1</span>');
  }
  return line
    .replace(/(#.*)$/g, '<span class="text-slate-500">$1</span>')
    .replace(/\b(FROM|WORKDIR|COPY|RUN|EXPOSE|CMD)\b/g, '<span class="text-purple-400">$1</span>')
    .replace(/"(.*?)"/g, '<span class="text-emerald-300">"$1"</span>');
}

function AnimatedCodeBlock({ snippet }) {
  const [visibleLines, setVisibleLines] = useState(0);
  const [copied, setCopied] = useState(false);
  const lines = snippet.code.split('\n');

  useEffect(() => {
    setVisibleLines(0);
    const interval = setInterval(() => {
      setVisibleLines((prev) => {
        if (prev >= lines.length) {
          clearInterval(interval);
          return prev;
        }
        return prev + 1;
      });
    }, 80);
    return () => clearInterval(interval);
  }, [snippet.id, lines.length]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(snippet.code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="relative rounded-xl overflow-hidden border border-white/[0.08] bg-[#0a0f18]">
      <div className="flex items-center justify-between px-4 py-2.5 border-b border-white/[0.06] bg-white/[0.02]">
        <div className="flex items-center gap-2">
          <div className="flex gap-1.5">
            <span className="w-2.5 h-2.5 rounded-full bg-red-500/60" />
            <span className="w-2.5 h-2.5 rounded-full bg-amber-500/60" />
            <span className="w-2.5 h-2.5 rounded-full bg-emerald-500/60" />
          </div>
          <span className="text-xs font-mono text-slate-500 ml-2">{snippet.label}</span>
        </div>
        <button
          onClick={handleCopy}
          className="p-1.5 rounded-md text-slate-500 hover:text-emerald-400 hover:bg-white/[0.04] transition-colors"
          aria-label="Copy code"
        >
          {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
        </button>
      </div>
      <pre className="p-4 overflow-x-auto text-[13px] leading-relaxed font-mono">
        <code>
          {lines.slice(0, visibleLines).map((line, i) => (
            <div key={i} className="flex">
              <span className="select-none text-slate-600 w-8 shrink-0 text-right pr-4">{i + 1}</span>
              <span
                className="text-slate-300"
                dangerouslySetInnerHTML={{ __html: highlightLine(line, snippet.lang) || '&nbsp;' }}
              />
            </div>
          ))}
          {visibleLines < lines.length && (
            <span className="inline-block w-2 h-4 bg-emerald-400 animate-blink ml-8" />
          )}
        </code>
      </pre>
    </div>
  );
}

export default function CodeSnippets({ embedded = false }) {
  const [activeTab, setActiveTab] = useState('terraform');
  const activeSnippet = SNIPPETS.find((s) => s.id === activeTab);

  return (
    <section className={embedded ? '' : 'relative py-24 sm:py-32 bg-white/[0.01]'}>
      <div className={embedded ? '' : 'max-w-7xl mx-auto px-4 sm:px-6 lg:px-8'}>
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          <ScrollReveal>
            {!embedded && (
              <span className="text-xs font-mono font-semibold text-emerald-400 uppercase tracking-widest">
                Developer Experience
              </span>
            )}
            <h2 className={`${embedded ? 'text-2xl' : 'mt-3 text-3xl sm:text-4xl'} font-extrabold text-white tracking-tight`}>
              {embedded ? 'Code Examples' : (
                <>Real infrastructure code, <span className="gradient-text-emerald">not mockups</span></>
              )}
            </h2>
            <p className="mt-4 text-slate-400 leading-relaxed">
              InfraSense generates copy-pasteable Terraform HCL, exposes its rule engine
              for customization, and outputs deployment-ready configurations — the same
              artifacts you'd use in a real infrastructure repository.
            </p>

            <div className="flex gap-2 mt-6">
              {SNIPPETS.map((s) => (
                <button
                  key={s.id}
                  onClick={() => setActiveTab(s.id)}
                  className={`px-4 py-2 rounded-lg text-sm font-mono font-medium transition-all ${
                    activeTab === s.id
                      ? 'bg-emerald-500/15 text-emerald-400 border border-emerald-500/30'
                      : 'text-slate-400 border border-white/[0.06] hover:border-white/10 hover:text-slate-300'
                  }`}
                >
                  {s.label}
                </button>
              ))}
            </div>
          </ScrollReveal>

          <ScrollReveal direction="left" delay={150}>
            {activeSnippet && <AnimatedCodeBlock snippet={activeSnippet} />}
          </ScrollReveal>
        </div>
      </div>
    </section>
  );
}
