import React, { useState, useEffect } from 'react';
import { Copy, Check, Code2 } from 'lucide-react';
import ScrollReveal from './ScrollReveal';

const SNIPPETS = [
  {
    id: 'terraform',
    label: 'Terraform HCL',
    lang: 'hcl',
    code: `# Generated by InfraSense Decision Engine
resource "aws_instance" "app_server" {
  ami           = "ami-0c55b159cbfafe1f0"
  instance_type = "t3.xlarge"
  count         = 2

  root_block_device {
    volume_size = 100
    volume_type = "gp3"
    iops        = 3000
    encrypted   = true
  }

  tags = {
    Name = "infrasence-compute-cluster"
  }
}`,
  },
  {
    id: 'rule',
    label: 'Rule Engine',
    lang: 'javascript',
    code: `// Custom heuristic rule in ruleEngine.js
{
  id: 'high_mem_db_rule',
  name: 'Database Memory Boost',
  condition: (input) => input.workload === 'database',
  applyWeight: (instance) => {
    if (instance.family.startsWith('r')) {
      return 25; // +25 score boost for memory-optimized
    }
    return 0;
  }
}`,
  },
  {
    id: 'docker',
    label: 'Docker Multi-Stage',
    lang: 'dockerfile',
    code: `# Production container build for cloud deployment
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --production=false
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD ["node", "dist/server.js"]`,
  },
];

function highlightLine(line, lang) {
  if (lang === 'hcl') {
    return line
      .replace(/(#.*)$/g, '<span class="text-slate-500">$1</span>')
      .replace(/"(.*?)"/g, '<span class="text-emerald-400">"$1"</span>')
      .replace(/\b(resource|provider|tags|count)\b/g, '<span class="text-purple-400">$1</span>')
      .replace(/\b(aws_\w+)\b/g, '<span class="text-sky-400">$1</span>');
  }
  if (lang === 'javascript') {
    return line
      .replace(/(\/\/.*)$/g, '<span class="text-slate-500">$1</span>')
      .replace(/"(.*?)"/g, '<span class="text-emerald-400">"$1"</span>')
      .replace(/\b(return|if|const|function)\b/g, '<span class="text-purple-400">$1</span>')
      .replace(/\b(\d+)\b/g, '<span class="text-amber-400">$1</span>');
  }
  return line
    .replace(/(#.*)$/g, '<span class="text-slate-500">$1</span>')
    .replace(/\b(FROM|WORKDIR|COPY|RUN|EXPOSE|CMD)\b/g, '<span class="text-purple-400">$1</span>')
    .replace(/"(.*?)"/g, '<span class="text-emerald-400">"$1"</span>');
}

function AnimatedCodeBlock({ snippet }) {
  const [visibleLines, setVisibleLines] = useState(0);
  const [copied, setCopied] = useState(false);
  const lines = snippet.code.split('\n');

  useEffect(() => {
    setVisibleLines(0);
    const interval = setInterval(() => {
      setVisibleLines((prev) => {
        if (prev >= lines.length) {
          clearInterval(interval);
          return prev;
        }
        return prev + 1;
      });
    }, 70);
    return () => clearInterval(interval);
  }, [snippet.id, lines.length]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(snippet.code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="mockup-window bg-slate-950 border border-slate-800 text-slate-100 shadow-2xl">
      <div className="flex items-center justify-between px-4 py-3 border-b border-slate-800/90 bg-slate-900/80">
        <div className="flex items-center gap-2">
          <div className="flex gap-1.5">
            <span className="w-3 h-3 rounded-full bg-rose-500/70" />
            <span className="w-3 h-3 rounded-full bg-amber-500/70" />
            <span className="w-3 h-3 rounded-full bg-emerald-500/70" />
          </div>
          <span className="text-xs font-mono text-slate-400 ml-2 font-medium">{snippet.label}</span>
        </div>
        <button
          onClick={handleCopy}
          className="flex items-center gap-1 px-2.5 py-1 rounded-lg text-xs font-mono text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          aria-label="Copy code"
        >
          {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
          <span>{copied ? 'Copied!' : 'Copy'}</span>
        </button>
      </div>
      <pre className="p-5 overflow-x-auto text-[13px] leading-relaxed font-mono">
        <code>
          {lines.slice(0, visibleLines).map((line, i) => (
            <div key={i} className="flex">
              <span className="select-none text-slate-600 w-8 shrink-0 text-right pr-4">{i + 1}</span>
              <span
                className="text-slate-300"
                dangerouslySetInnerHTML={{ __html: highlightLine(line, snippet.lang) || '&nbsp;' }}
              />
            </div>
          ))}
          {visibleLines < lines.length && (
            <span className="inline-block w-2 h-4 bg-blue-400 animate-blink ml-8" />
          )}
        </code>
      </pre>
    </div>
  );
}

export default function CodeSnippets({ embedded = false }) {
  const [activeTab, setActiveTab] = useState('terraform');
  const activeSnippet = SNIPPETS.find((s) => s.id === activeTab);

  return (
    <section className={embedded ? '' : 'relative py-20 sm:py-28 bg-white/70'}>
      <div className={embedded ? '' : 'max-w-7xl mx-auto px-4 sm:px-6 lg:px-8'}>
        <div className="grid lg:grid-cols-2 gap-10 lg:gap-14 items-center">
          <ScrollReveal>
            {!embedded && (
              <span className="text-xs font-bold font-mono text-blue-600 uppercase tracking-widest block mb-2">
                Developer Experience
              </span>
            )}
            <h2 className={`${embedded ? 'text-2xl' : 'text-3xl sm:text-4xl lg:text-5xl'} font-extrabold text-slate-900 tracking-tight leading-tight`}>
              {embedded ? 'Code Examples' : (
                <>Production code, <br /><span className="gradient-text-blue">ready to deploy</span></>
              )}
            </h2>
            <p className="mt-4 text-sm sm:text-base text-slate-600 leading-relaxed font-normal">
              InfraSense generates copy-pasteable Terraform HCL, exposes its heuristic rule engine for customization, and outputs deployment-ready configurations — the same artifacts you'd use in a real infrastructure repository.
            </p>

            <div className="flex flex-wrap gap-2 mt-6">
              {SNIPPETS.map((s) => (
                <button
                  key={s.id}
                  onClick={() => setActiveTab(s.id)}
                  className={`px-4 py-2 rounded-xl text-xs font-mono font-bold transition-all ${
                    activeTab === s.id
                      ? 'bg-blue-600 text-white shadow-sm shadow-blue-500/20'
                      : 'bg-white text-slate-600 border border-slate-200 hover:text-slate-900 hover:bg-slate-50'
                  }`}
                >
                  {s.label}
                </button>
              ))}
            </div>
          </ScrollReveal>

          <ScrollReveal direction="left" delay={150}>
            {activeSnippet && <AnimatedCodeBlock snippet={activeSnippet} />}
          </ScrollReveal>
        </div>
      </div>
    </section>
  );
}
